apiVersion: v1
kind: Service
metadata:
{{- if .Values.bind9.serviceName }}
  name: {{ .Values.bind9.serviceName }}
{{- else }}
  name: {{ .Release.Name }}-bind9
{{- end }}
  labels:
    app: bind9
    release: {{ .Release.Name }}
spec:
  selector:
    app: bind9
    release: {{ .Release.Name }}
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
